# aws cloudformation create-stack --capabilities CAPABILITY_NAMED_IAM --stack-name ecr-us-east-1-demo --template-body file://ecr.yaml

AWSTemplateFormatVersion: '2010-09-09'

Description: >
  This template creates ECR Docker image repositories with an IAM cross account access role.

Resources:
### IAM ###
  DemoEcrCrossAccountAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DemoEcrCrossAccountAccessRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::<AWS ACCOUNT NUMBER 1>:root
                - arn:aws:iam::<AWS ACCOUNT NUMBER 2>:root
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser'

### ECR ###
  DemoDockerAppRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: demo-docker-app
      RepositoryPolicyText:
        Version: '2012-10-17'
        Statement:
        - Sid: AllowPushPull
          Effect: Allow
          Principal:
            AWS:
              - arn:aws:iam::<AWS ACCOUNT NUMBER 1>:root
              - arn:aws:iam::<AWS ACCOUNT NUMBER 1>:root
              - !GetAtt [DemoEcrCrossAccountAccessRole, Arn]
          Action:
          - ecr:GetDownloadUrlForLayer
          - ecr:BatchGetImage
          - ecr:BatchCheckLayerAvailability
          - ecr:PutImage
          - ecr:InitiateLayerUpload
          - ecr:UploadLayerPart
          - ecr:CompleteLayerUpload
          - ecr:ListImages
          - ecr:DescribeTaskDefinition

Outputs:
  DemoDockerAppRepo:
    Description: ECR repository for Demo Docker App
    Value: !Ref 'DemoDockerAppRepo'